name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          # Создаём файл ответов для Buildozer
          echo "y" | buildozer -v android debug || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./bin/*.apk